#include <cstdlib>
#include <cstdio>
#include <iostream>
#include <string>
#include <iterator>
#include <algorithm>
#include <iomanip>
#include "util/util.h"
#include "fm_core/fm_model_new.h"
#include "libfm/src/Data.h"
#include "libfm/src/fm_learn.h"
#include "libfm/src/fm_learn_sgd.h"
#include "libfm/src/fm_learn_sgd_element_new.h"
